#!/usr/bin/env python3
"""Build the GitHub Pages static bundle for the IPO watch dashboard."""

from __future__ import annotations

import html
import json
import re
import shutil
from pathlib import Path

from validate_report_quality import validate_publish_contract


ROOT = Path(__file__).resolve().parents[1]
PUBLISH_DIR = ROOT / "publish" / "ipo-watch-dashboard"
DASHBOARD_DIR = ROOT / "dashboard"
MOBILE_DIR = ROOT / "mobile"
REPORTS_JS = DASHBOARD_DIR / "reports.js"
REPORT_DATE = "2026-07-10"


def parse_js_object(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"=\s*(\{.*\})\s*;", text, re.S)
    if not match:
        raise ValueError(f"Cannot parse {path}")
    return json.loads(match.group(1))


def reset_publish_dir() -> None:
    PUBLISH_DIR.mkdir(parents=True, exist_ok=True)
    for child in PUBLISH_DIR.iterdir():
        if child.name in {".git", ".gitignore", "docs"}:
            continue
        if child.is_dir():
            shutil.rmtree(child)
        else:
            child.unlink()


def copy_path(source: Path) -> None:
    if not source.exists():
        raise FileNotFoundError(source)
    target = PUBLISH_DIR / source.relative_to(ROOT)
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)


def copy_dashboard() -> None:
    for source in DASHBOARD_DIR.rglob("*"):
        if source.is_file():
            copy_path(source)


def copy_mobile() -> None:
    for source in MOBILE_DIR.rglob("*"):
        if source.is_file():
            copy_path(source)


def copy_quality_tooling() -> None:
    for relative in (
        ".python-version",
        "requirements.txt",
        "requirements-dev.txt",
        "scripts/build_github_pages_publish.py",
        "scripts/generate_skill_structured_reports.py",
        "scripts/standardize_overview_reports.py",
        "scripts/upgrade_current_reports.py",
        "scripts/validate_report_quality.py",
        "tests/test_current_report_integrity.py",
        "tests/test_finance_visuals.py",
        "tests/test_overview_standardization.py",
        "tests/test_publish_contract.py",
        "tests/test_report_quality_gate.py",
        "tests/test_report_upgrade.py",
        "tests/test_responsive_contract.py",
    ):
        copy_path(ROOT / relative)


def local_refs(html_path: Path) -> set[Path]:
    text = html_path.read_text(encoding="utf-8", errors="ignore")
    refs: set[Path] = set()
    patterns = [
        r"""(?:src|href)=["']([^"']+)["']""",
        r"""url\(["']?([^"')]+)["']?\)""",
    ]
    for pattern in patterns:
        for raw in re.findall(pattern, text):
            ref = html.unescape(raw.strip())
            if not ref or ref.startswith(("http://", "https://", "data:", "#", "mailto:", "javascript:")):
                continue
            candidate = (html_path.parent / ref).resolve()
            try:
                candidate.relative_to(ROOT)
            except ValueError:
                continue
            if candidate.exists() and candidate.is_file():
                refs.add(candidate)
    return refs


def copy_current_reports() -> list[Path]:
    reports = parse_js_object(REPORTS_JS)
    copied: list[Path] = []
    for company, report in reports.items():
        if not isinstance(report, dict):
            continue
        for key in ("overviewUrl", "researchUrl", "assetUrl"):
            raw = report.get(key)
            if not isinstance(raw, str) or not raw:
                continue
            source = (DASHBOARD_DIR / raw).resolve()
            copy_path(source)
            copied.append(source)
            if source.suffix.lower() in {".html", ".htm"}:
                for ref in local_refs(source):
                    copy_path(ref)
    return copied


def write_root_files(report_count: int) -> None:
    (PUBLISH_DIR / ".nojekyll").write_text("", encoding="utf-8")
    (PUBLISH_DIR / ".codex-publish-target").write_text(
        "Generated by scripts/build_github_pages_publish.py\n", encoding="utf-8"
    )
    (PUBLISH_DIR / "index.html").write_text(
        """<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="refresh" content="0; url=dashboard/index.html">
  <title>A股 IPO Watch</title>
</head>
<body>
  <p><a href="dashboard/index.html">打开 A股 IPO Watch 看板</a></p>
</body>
</html>
""",
        encoding="utf-8",
    )
    (PUBLISH_DIR / "README.md").write_text(
        f"""# A股 IPO Watch 看板

本仓库用于通过 GitHub Pages 发布 A 股待上市企业看板。

- 首页：`dashboard/index.html`
- 报告数量：{report_count} 份 HTML
- 报告日期：{REPORT_DATE}，北京时间
- 说明：本项目仅作研究分析，不构成投资建议。

数据和结论以各页面标注的官方披露文件、公告日期和来源列表为准。
""",
        encoding="utf-8",
    )


def validate_bundle() -> None:
    required = [
        PUBLISH_DIR / "index.html",
        PUBLISH_DIR / "dashboard" / "index.html",
        PUBLISH_DIR / "mobile" / "index.html",
        PUBLISH_DIR / "mobile" / "app.js",
        PUBLISH_DIR / "mobile" / "styles.css",
        PUBLISH_DIR / "dashboard" / "app.js",
        PUBLISH_DIR / "dashboard" / "reports.js",
        PUBLISH_DIR / "dashboard" / "data.js",
        PUBLISH_DIR / "dashboard" / "assets" / "ipo-hero.png",
    ]
    missing = [str(path.relative_to(PUBLISH_DIR)) for path in required if not path.exists()]
    if missing:
        raise SystemExit("Missing publish files: " + ", ".join(missing))


def main() -> None:
    quality_errors = validate_publish_contract(ROOT)
    if quality_errors:
        raise SystemExit("REPORT_QUALITY_GATE_FAILED\n" + "\n".join(quality_errors))
    reset_publish_dir()
    copy_dashboard()
    copy_mobile()
    copy_quality_tooling()
    copied = copy_current_reports()
    write_root_files(len([path for path in copied if path.suffix.lower() in {".html", ".htm"}]))
    validate_bundle()
    print(f"PUBLISH_BUNDLE_OK {PUBLISH_DIR}")


if __name__ == "__main__":
    main()
